ในการติดตั้ง Docker Compose บน Ubuntu 20.04 LTS (focal image) สำหรับสถาปัตยกรรม `amd64` ที่ถูกสร้างเมื่อวันที่ 30 สิงหาคม 2024 คุณสามารถทำตามขั้นตอนด้านล่างนี้:

### ขั้นตอนที่ 1: อัพเดตระบบ
อัพเดตแพ็กเกจและข้อมูล repository ให้เป็นปัจจุบัน

```bash
sudo apt update
sudo apt upgrade
```

### ขั้นตอนที่ 2: ติดตั้ง Docker
1. ลบ Docker เวอร์ชันเก่า (ถ้ามี)

   ```bash
   sudo apt remove docker docker-engine docker.io containerd runc
   ```

2. ติดตั้งแพ็กเกจที่จำเป็น

   ```bash
   sudo apt install apt-transport-https ca-certificates curl software-properties-common
   ```

3. เพิ่ม Docker GPG key

   ```bash
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
   ```

4. เพิ่ม Docker repository

   ```bash
   echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
   ```

5. อัพเดตและติดตั้ง Docker

   ```bash
   sudo apt update
   sudo apt install docker-ce docker-ce-cli containerd.io
   ```

6. ตรวจสอบการติดตั้ง Docker

   ```bash
   docker --version
   ```

### ขั้นตอนที่ 3: ติดตั้ง Docker Compose
1. ดาวน์โหลด Docker Compose เวอร์ชันล่าสุด

   ```bash
   sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   ```

2. ตั้งค่า permission ให้ไฟล์สามารถรันได้

   ```bash
   sudo chmod +x /usr/local/bin/docker-compose
   ```

3. ตรวจสอบการติดตั้ง Docker Compose

   ```bash
   docker-compose --version
   ```

### ขั้นตอนที่ 4: ตั้งค่า Docker ให้สามารถรันได้โดยไม่ต้องใช้ sudo (ถ้ายังไม่ได้ตั้งค่า)
1. เพิ่มผู้ใช้ของคุณในกลุ่ม Docker

   ```bash
   sudo usermod -aG docker ${USER}
   ```

2. รีสตาร์ทเครื่องหรือออกจากระบบแล้วล็อกอินใหม่

### ขั้นตอนที่ 5: ทดสอบการใช้งาน
คุณสามารถทดสอบการใช้งาน Docker Compose ด้วยการสร้างไฟล์ `docker-compose.yml` และรันด้วยคำสั่ง:

```bash
docker-compose up
```

หลังจากทำตามขั้นตอนเหล่านี้แล้ว คุณจะสามารถใช้ Docker และ Docker Compose บน Ubuntu 20.04 LTS ได้
